const Foodapi = [
    {
      id: 1,
      title: 'Breakfast Item 1',
      description: 'Delicious breakfast item',
      foodType: 'Breakfast',
      price: '$10',
      category: 'Breakfast',
      imageUrl: 'https://img.freepik.com/free-photo/fresh-pasta-with-hearty-bolognese-parmesan-cheese-generated-by-ai_188544-9469.jpg',
    },
    {
      id: 2,
      title: 'Lunch Item 1',
      description: 'Delicious lunch item',
      foodType: 'Lunch',
      price: '$15',
      category: 'Lunch',
      imageUrl:'https://img.freepik.com/free-photo/fresh-pasta-with-hearty-bolognese-parmesan-cheese-generated-by-ai_188544-9469.jpg',
    },
    {
      id: 3,
      title: 'Dinner Item 1',
      description: 'Delicious dinner item',
      foodType: 'Dinner',
      price: '$20',
      category: 'Dinner',
      imageUrl:'https://img.freepik.com/free-photo/fresh-pasta-with-hearty-bolognese-parmesan-cheese-generated-by-ai_188544-9469.jpg',
    },
    {
      id: 4,
      title: 'Breakfast Item 2',
      description: 'Tasty breakfast item',
      foodType: 'Breakfast',
      price: '$8',
      category: 'Breakfast',
      imageUrl:'https://img.freepik.com/free-photo/fresh-pasta-with-hearty-bolognese-parmesan-cheese-generated-by-ai_188544-9469.jpg',
    },
    {
      id: 5,
      title: 'Lunch Item 2',
      description: 'Tasty lunch item',
      foodType: 'Lunch',
      price: '$12',
      category: 'Lunch',
      imageUrl:'https://img.freepik.com/free-photo/fresh-pasta-with-hearty-bolognese-parmesan-cheese-generated-by-ai_188544-9469.jpg',
    },
    {
      id: 6,
      title: 'Dinner Item 2',
      description: 'Tasty dinner item',
      foodType: 'Dinner',
      price: '$18',
      category: 'Dinner',
      imageUrl:'https://img.freepik.com/free-photo/fresh-pasta-with-hearty-bolognese-parmesan-cheese-generated-by-ai_188544-9469.jpg',
    },
    {
      id: 7,
      title: 'Breakfast Item 3',
      description: 'Scrumptious breakfast item',
      foodType: 'Breakfast',
      price: '$9',
      category: 'Breakfast',
      imageUrl:'https://img.freepik.com/free-photo/fresh-pasta-with-hearty-bolognese-parmesan-cheese-generated-by-ai_188544-9469.jpg',
    },
    {
      id: 8,
      title: 'Lunch Item 3',
      description: 'Scrumptious lunch item',
      foodType: 'Lunch',
      price: '$14',
      category: 'Lunch',
      imageUrl:'https://img.freepik.com/free-photo/fresh-pasta-with-hearty-bolognese-parmesan-cheese-generated-by-ai_188544-9469.jpg',
    },
    {
      id: 9,
      title: 'Dinner Item 3',
      description: 'Scrumptious dinner item',
      foodType: 'Dinner',
      price: '$22',
      category: 'Dinner',
      imageUrl:'https://img.freepik.com/free-photo/fresh-pasta-with-hearty-bolognese-parmesan-cheese-generated-by-ai_188544-9469.jpg',
    },
    {
      id: 10,
      title: 'Snack Item 1',
      description: 'Yummy snack item',
      foodType: 'Snack',
      price: '$5',
      category: 'Snack',
      imageUrl:'https://img.freepik.com/free-photo/fresh-pasta-with-hearty-bolognese-parmesan-cheese-generated-by-ai_188544-9469.jpg',
    },
  ];
  export default Foodapi